project_id = "suinpiejctltkfmczxrw"

[functions.create-payment]
verify_jwt = true

[functions.process-payment-webhook]
verify_jwt = false

[functions.analyze-image]
verify_jwt = true

[functions.create-user]
verify_jwt = true
